export const ADD_TRANSACTION = 'TRANSACTION/ADD_TRANSACTION'
export const REQUEST_TRANSACTIONS = 'TRANSACTION/REQUEST_TRANSACTIONS'
export const RECEIVE_TRANSACTIONS = 'TRANSACTION/RECEIVE_TRANSACTIONS'
